export const products = [
  {
    id: 1,
    name: "Missha M Perfect Cover BB krem, SPF 42 PA+++",
    category: "Yuz uchun",
    price: 85000,
    rating: 4.9,
    reviews: 1420,
    description: "Dunyoga mashhur Missha BB kremi. Yuzdagi kamchiliklarni mukammal yashiradi va quyoshdan himoya qiladi.",
    image: "https://images.unsplash.com/photo-1631730359585-38a4935cbec4?q=80&w=800&auto=format&fit=crop",
    featured: true,
  },
  {
    id: 2,
    name: "Garnier Micellar tozalovchi suvi, barcha teri turlari uchun",
    category: "Terini parvarishlash",
    price: 45000,
    rating: 4.8,
    reviews: 890,
    description: "Makiyajni qiyinchiliksiz va ishqalashsiz tozalash uchun ideal vosita.",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop",
    featured: true,
  },
  {
    id: 3,
    name: "Maybelline New York Super Stay mat pomadasi",
    category: "Lab uchun",
    price: 68000,
    rating: 4.7,
    reviews: 2150,
    description: "16 soatgacha saqlanib turuvchi super chidamli mat pomada.",
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800&auto=format&fit=crop",
    featured: true,
  },
  {
    id: 4,
    name: "COSRX Salitsil kislotali tozalovchi penka",
    category: "Terini parvarishlash",
    price: 95000,
    rating: 4.8,
    reviews: 645,
    description: "Yog'li va muammoli terilar uchun Koreya yuz yuvish vositasi.",
    image: "https://images.unsplash.com/photo-1629198688000-71f23e745b6e?q=80&w=800&auto=format&fit=crop",
    featured: false,
  },
  {
    id: 5,
    name: "L'Oreal Paris Elseve Soch uchun yog'-ekstrakt",
    category: "Soch parvarishi",
    price: 52000,
    rating: 4.6,
    reviews: 1320,
    description: "Sochlarga jilo va yumshoqlik baxsh etuvchi universal yog'.",
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=800&auto=format&fit=crop",
    featured: false,
  },
  {
    id: 6,
    name: "Vivienne Sabo Cabaret Premiere qora tush",
    category: "Ko'z uchun",
    price: 48000,
    rating: 4.9,
    reviews: 3512,
    description: "Kipriklarga sahna hajmini beruvchi afsonaviy qora tush.",
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=800&auto=format&fit=crop",
    featured: false,
  }
];
